_target_: src.models.trajpred.TrajPred
optimizer:
  lr: 1e-4
  weight_decay: 1e-1
  beta1 : 0.9
  beta2 : 0.95

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.amelia.AmeliaTF
  config: 
    encoder:
      in_size: 4
      embed_size: 256
      interp_flag: ${data.dataset.config.encode_interp_flag}

      hist_len: ${data.dataset.config.hist_len}
      pred_lens: ${data.dataset.config.pred_lens}
      
      T_size: ${data.dataset.config.traj_len}
      A_size: ${data.dataset.config.k_agents}
            
      add_context: true
      context_encoder_type: 'v0'
      contextnet:
        in_size: 5
        embed_size: ${model.net.config.encoder.embed_size}
        num_mlp_layers: 1
        num_satt_layers: 1
        num_heads: 8
        dropout: 0.0
        bias: True
        num_vectors: ${data.dataset.config.num_polylines}

      # context_encoder_type: 'v0'
      contextnet_v0: 
        in_size: 5 
        embed_size: ${model.net.config.encoder.embed_size}
        num_layers: 2
        num_vectors: ${data.dataset.config.num_polylines}

      # context_encoder_type: 'v1'
      contextnet_v1:
        in_size: 5
        embed_size: ${model.net.config.encoder.embed_size}
        ker_size: 4
        num_layers: 2
        num_vectors: ${data.dataset.config.num_polylines}

      # context_encoder_type: 'v2'
      contextnet_v2:
        in_size: 5
        embed_size: ${model.net.config.encoder.embed_size}
        ker_size: 4
        num_layers: 2
        num_satt_layers: 1
        num_heads: 8
        dropout: 0.0
        bias: True
        num_vectors: ${data.dataset.config.num_polylines}

      # context_encoder_type: 'v3'
      contextnet_v3:
        in_size: 5
        embed_size: ${model.net.config.encoder.embed_size}
        ker_size: 4
        num_layers: 2
        num_satt_layers: 1
        num_heads: 8
        dropout: 0.0
        bias: True
        num_vectors: ${data.dataset.config.num_polylines}

      num_satt_pre_blocks: 1
      num_catt_pre_blocks: 1
      num_satt_blocks: 1
      num_catt_blocks: 1
      num_satt_post_blocks: 1

      num_layers: 5
      num_heads: 8
      dropout: 0.0
      bias: True 

    decoder:
      num_dims: 7
      num_futures: 4

extra_params: 
  propagation: null
  tag: null
  use_agent_masks: false
  
  seen_airports: ${data.extra_params.data_prep.seen_airports}
  unseen_airports: ${data.extra_params.data_prep.unseen_airports}
  
  asset_dir: ${paths.assets_dir}
  plot_dir: ${paths.vis_dir}
  plot_train: False
  plot_val: False
  plot_test: False 
  plot_every_n: 100
  plot_after_n_epochs: 20