defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - lr_monitor.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val_ade/t=max"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  save_weights_only: True
  
early_stopping:
  monitor: "val_ade/t=max"
  patience: 10
  mode: "min"

model_summary:
  max_depth: -1
