ckpt: kjfk
type: Single-Airport

defaults:
  - data: kjfk.yaml
  - model: marginal.yaml
  - callbacks: default.yaml
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu.yaml
  - paths: version8.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - _self_

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation

ckpt_dir: ${paths.base_dir}/checkpoints
ckpt_path: ${ckpt_dir}/${type}/${ckpt}/${ckpt}_critical.ckpt
# seed for random number generators in pytorch, numpy and python.random
seed: 42